version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test gem
          command: |
            gem install bundler
            export VERSION=0.0.<<pipeline.number>>
            bundle --version
            bundle install
            rake test
      - store_test_results:
          path: ./test-results
      - setup-rubygems_key
      - run:
          name: Build and push gem
          command: |
            export VERSION=0.0.<<pipeline.number>>
            gem build emery.gemspec
            if [ $CIRCLE_BRANCH = "main" ]; then
              export VERSION=0.0.<<pipeline.number>>
              gem push --key rubygems emery-$VERSION.gem
            else
              echo "Will not release - not running on main branch"
            fi

commands:
  setup-rubygems_key:
    steps:
      - run:
          name: Write key
          command: |
            mkdir ~/.gem
            tee > ~/.gem/credentials \<<END
            ---
            :rubygems_api_key: $RUBYGEMS_API_KEY
            END
            chmod 600 ~/.gem/credentials

workflows:
  build-release:
    jobs:
      - build:
          context: emery